### ISSUE TITLE
Timing will not work where generator returned.

### ISSUE THREAD

**Issue by GrahamDumpleton** [paylogic/wsgi-statsd#1]
You are using:

```
        # Time the call.
        start = time.time()
        result = self.app(environ, start_response_wrapper)
        stop = time.time()
```

In the case of the WSGI application returning a generator, all that will do is time how long it took the generator object to be created. The code of the application will not be invoked until the first item is pulled from the generator by the WSGI server.

So for that case you aren't actually timing how long the application code actually takes.

Timing a WSGI application in all the different scenarios is a lot more complicated than this and there lots of gotchas in getting it right. :-)

**Comment by wlansu** [comment]
Thanks for your comment, Graham, I'll look into it.

**Comment by bubenkoff** [comment]
that's quite easy to solve by wrapping an application properly - so returning another iterator which does the timing

**Comment by bubenkoff** [comment]
@wlansu http://en.wikipedia.org/wiki/Web_Server_Gateway_Interface
https://www.python.org/dev/peps/pep-3333/

**Comment by wlansu** [comment]
This should now work in version 0.2.0. Thanks again for pointing this out, Graham.
