### ISSUE TITLE
Status will not be set when exception occurs before start_response().

### ISSUE THREAD

**Issue by GrahamDumpleton** [paylogic/wsgi-statsd#3]
In ``send_stats()``:

```
status = interception['status'].split()[0]
```

will fail if ``start_response()`` hadn't been called before the exception occurred.

This will be relevant where timing exceptions is enabled.

**Comment by bubenkoff** [comment]
do not agree :)
```
if interception:
```
is there for that reason

**Comment by GrahamDumpleton** [comment]
Okay, missed that one. Can't win every time when just eyeballing this. :-)

Might suggest you be tolerant of it being missing though in case you decide later to start populating interception with other things prior to start_response() being called. Depends of how defensive you want to be.

**Comment by bubenkoff** [comment]
i agree it looks sloppy and should be better
