### ISSUE TITLE
PATH_INFO should be encoded with a configurable separator

### ISSUE THREAD

**Issue by bubenkoff** [paylogic/wsgi-statsd#5]
ATM '.' is used as a separator of the request path bits. This makes it impossible to query data back the way you want to get an overview of all requests coming to your application via say graphite url api:
app.some.url.POST.200
app.some.other.url.POST.200

you cannot graph the data via app.some.*.POST.200 as graphite considers * as anything except the '.'.
So it will be possible to work with stats data the way path is encoded with some other than '.' separator, which is configurable at the constructor of the middleware:

application = StatsdTimingMiddleware(application, client, separator='_')

and then the key values will be like:

app.some_url.POST.200
app.some_other_url.POST.200

note that last 2 bits method and response can stay as they are - because they are predictable.
Actually, i think it would be good if the default separator will be '_' - covers way more use-cases.

**Comment by wlansu** [comment]
Implemented in 0.2.4.
